stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     -name: TestselfhostedPool
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"
- stage: dev_deploy
  jobs:
  - deployment: dev_deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'dev-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world !!!"
